
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  template: template0

development:
  <<: *default
  database: task2_development


test:
  <<: *default
  database: task2_test


production:
  <<: *default
  database: task2_production
  username: task2
  password: <%= ENV['TASK2_DATABASE_PASSWORD'] %>
